name: e2e

on:
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: e2e-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ secrets.SEED_MNEMONIC != '' && secrets.BLOCKFROST_KEY != '' }}
    env:
      CI: true
      OGMIOS_URL: ${{ secrets.OGMIOS_URL }}
      KUPO_URL: ${{ secrets.KUPO_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: üì¶ Setup pnpm
        uses: pnpm/action-setup@v4

      - name: üì¶ Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          # 22.5.0 is bugged, will make "latest" again after fixed
          node-version: "22.4.1"

      - name: üõ†Ô∏è Install dependencies
        run: pnpm install --frozen-lockfile

      - name: üéÅ Run build
        run: pnpm build
        env:
          NODE_ENV: production

      - name: Run e2e tests
        run: pnpm -w --filter @blaze-cardano/e2e test
        env:
          NODE_ENV: production
          SEED_MNEMONIC: ${{ secrets.SEED_MNEMONIC }}
          BLOCKFROST_KEY: ${{ secrets.BLOCKFROST_KEY }}
